[package]
name = "inventory"
version = "0.1.4"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Typed distributed plugin registration"
repository = "https://github.com/dtolnay/inventory"
documentation = "https://docs.rs/inventory"
readme = "README.md"
edition = "2018"

[dependencies]
ctor = "0.1"
ghost = "0.1.1"
inventory-impl = { version = "=0.1.4", path = "impl" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[workspace]
members = ["impl"]

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
